### ISSUE TITLE
Getting error: Cannot read property 'deploy_uuid' of undefined

### ISSUE THREAD

**Issue by ishan123456789** [ionic-team/cordova-plugin-ionic#158]
**cordova plugin ls output:**
```
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-fcm-with-dependecy-updated 2.2.4 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic 5.2.4 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**ionic info output:**
```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/Users/75way/.nvm/versions/node/v8.12.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.4, cordova-plugin-ionic-webview 2.1.4, (and 11 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/75way/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 7.0.0
   NodeJS            : v8.12.0 (/Users/75way/.nvm/versions/node/v8.12.0/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.3.1 Build version 9E501
```

**Describe the bug**
```
Error: Uncaught (in promise): TypeError: Cannot read property 'deploy_uuid' of undefined
TypeError: Cannot read property 'deploy_uuid' of undefined
    at t.<anonymous> (http://localhost:8080/build/vendor.js:1:1100632)
    at http://localhost:8080/build/vendor.js:1:1082665
    at Object.next (http://localhost:8080/build/vendor.js:1:1082770)
    at s (http://localhost:8080/build/vendor.js:1:1081748)
    at t.invoke (http://localhost:8080/build/polyfills.js:3:14976)
    at Object.t._inner.t._inner.fork.onInvoke (http://localhost:8080/build/vendor.js:1:88471)
    at t.invoke (http://localhost:8080/build/polyfills.js:3:14946)
    at r.run (http://localhost:8080/build/polyfills.js:3:10143)
    at http://localhost:8080/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8080/build/polyfills.js:3:15660) {rejection: TypeError: Cannot read property 'deploy_uuid' of undefined, promise: t, zone: r, task: e, stack: (...)…}
```

```
TypeError: Cannot read property 'deploy_uuid' of undefined {__zone_symbol__currentTask: e, stack: (...), message: "Cannot read property 'deploy_uuid' of undefined"} TypeError: Cannot read property 'deploy_uuid' of undefined
    at t.<anonymous> (http://localhost:8080/build/vendor.js:1:1100632)
    at http://localhost:8080/build/vendor.js:1:1082665
    at Object.next (http://localhost:8080/build/vendor.js:1:1082770)
    at s (http://localhost:8080/build/vendor.js:1:1081748)
    at t.invoke (http://localhost:8080/build/polyfills.js:3:14976)
    at r.run (http://localhost:8080/build/polyfills.js:3:10143)
    at http://localhost:8080/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8080/build/polyfills.js:3:15660)
    at r.runTask (http://localhost:8080/build/polyfills.js:3:10834)
    at o (http://localhost:8080/build/polyfills.js:3:7894)
```

**To Reproduce**
I found reference to 
```deployInfo.deploy_uuid```  in `ionic-pro.module.js`
I get an error when I try this

```
  throwError(e) {
    Pro.monitoring.exception(new Error(e));
  }
```

**Comment by jcesarmobile** [comment]
What's the version of `@ionic/pro` in your package.json?

I can't reproduce with 2.0.3, and there are no references of `deploy_uuid` there.

Can you test with that version?
