### ISSUE TITLE
NOT UPDATE ON ANDROID

### ISSUE THREAD

**Issue by boris1690** [ionic-team/cordova-plugin-ionic#183]
When i deploy new update, this update correct on IOS but on ANDROID not update any change my package is:

{
    "name": "pushdeploy",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "start": "ionic-app-scripts serve",
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build --prod",
        "lint": "ionic-app-scripts lint"
    },
    "config": {
        "ionic_webpack": "./src/config/webpack.config.js"
    },
    "dependencies": {
        "@angular/animations": "5.2.11",
        "@angular/common": "5.2.11",
        "@angular/compiler": "5.2.11",
        "@angular/compiler-cli": "5.2.11",
        "@angular/core": "5.2.11",
        "@angular/forms": "5.2.11",
        "@angular/http": "5.2.11",
        "@angular/platform-browser": "5.2.11",
        "@angular/platform-browser-dynamic": "5.2.11",
        "@angular/router": "^5.2.11",
        "@ionic-native/core": "~4.15.0",
        "@ionic-native/google-analytics": "^4.0.0",
        "@ionic-native/header-color": "^4.0.0",
        "@ionic-native/keyboard": "^4.10.0",
        "@ionic-native/onesignal": "^4.3.3",
        "@ionic-native/screen-orientation": "^3.12.1",
        "@ionic-native/social-sharing": "^3.12.1",
        "@ionic-native/splash-screen": "~4.15.0",
        "@ionic-native/status-bar": "~4.15.0",
        "@ionic/pro": "2.0.3",
        "@ionic/storage": "2.2.0",
        "@ngrx/core": "^1.2.0",
        "@ngrx/effects": "^4.1.1",
        "@ngrx/store": "^4.1.1",
        "cordova-android": "7.1.1",
        "cordova-plugin-device": "^2.0.2",
        "cordova-plugin-file": "6.0.1",
        "cordova-plugin-file-transfer": "1.7.1",
        "cordova-plugin-ionic": "5.2.7",
        "cordova-plugin-ionic-keyboard": "^2.1.3",
        "cordova-plugin-ionic-webview": "^2.2.0",
        "cordova-plugin-splashscreen": "^5.0.2",
        "cordova-plugin-statusbar": "^2.4.2",
        "cordova-plugin-whitelist": "^1.3.3",
        "ionic-angular": "3.9.2",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "jquery": "^3.3.1",
        "lodash": "^4.17.10",
        "ng-pipes": "^0.1.2",
        "ngrx-store-ionic-storage": "^4.2.0",
        "ngrx-store-localstorage": "^5.0.0",
        "onesignal-cordova-plugin": "^2.4.4",
        "rxjs": "^5.5.5",
        "rxjs-compat": "^6.3.3",
        "sw-toolbox": "3.6.0",
        "zone.js": "^0.8.26"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.2.0",
        "typescript": "~2.7"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-whitelist": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-ionic-webview": {
                "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
            },
            "cordova-plugin-ionic-keyboard": {},
            "cordova-plugin-ionic": {
                "APP_ID": "896459d6",
                "CHANNEL_NAME": "Production",
                "UPDATE_METHOD": "auto",
                "UPDATE_API": "https://api.ionicjs.com",
                "MAX_STORE": "2",
                "MIN_BACKGROUND_DURATION": "30"
            }
        },
        "platforms": [
            "android"
        ]
    }
}

**Comment by boris1690** [comment]
Yes, I've tested on rea devide, i found the following issue "Sync failed. Defaulting to last available version", but on iOs not present the issue.

**Comment by HudsonAfonso** [comment]
+1

**Comment by jcesarmobile** [comment]
Please, don't comment with just +1, try to provide additional information to help debug the issue.

If you got the "Sync failed. Defaulting to last available version" message, there should be another one error message right before.

**Comment by HudsonAfonso** [comment]
+1 = same problem....


11-19 11:44:29.916 19040 19120 I IONIC.DEPLOY.EXTRACT: Progress: 73%
11-19 11:44:29.921 19040 19120 I IONIC.DEPLOY.EXTRACT: Progress: 75%
11-19 11:44:29.929 19040 19120 I IONIC.DEPLOY.EXTRACT: Progress: 77%
11-19 11:44:29.929 19040 19120 I IONIC.DEPLOY.EXTRACT: Progress: 80%
11-19 11:44:29.930 19040 19120 I IONIC.DEPLOY.EXTRACT: Progress: 82%
11-19 11:44:29.930 19040 19120 I IONIC.DEPLOY.EXTRACT: Progress: 84%
11-19 11:44:29.937 19040 19120 I IONIC.DEPLOY.EXTRACT: Progress: 86%
11-19 11:44:29.941 19040 19120 I IONIC.DEPLOY.REMOVE: Removed www.zip
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: Pre-redirect cordova injection exception: java.io.FileNotFoundException: /data/user/0/..../app_.../index.html (No such file or directory)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at java.io.FileInputStream.open0(Native Method)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at java.io.FileInputStream.open(FileInputStream.java:200)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at java.io.FileReader.<init>(FileReader.java:72)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at com.ionicframework.deploy.IonicDeploy.getStringFromFile(IonicDeploy.java:125)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at com.ionicframework.deploy.IonicDeploy.redirect(IonicDeploy.java:973)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at com.ionicframework.deploy.IonicDeploy.unzip(IonicDeploy.java:927)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at com.ionicframework.deploy.IonicDeploy.access$400(IonicDeploy.java:79)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at com.ionicframework.deploy.IonicDeploy$DownloadTask$1.run(IonicDeploy.java:1307)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-19 11:44:29.943 19040 19120 I IONIC.DEPLOY.REDIRECT: 	at java.lang.Thread.run(Thread.java:764)

**Comment by jcesarmobile** [comment]
Based on this information, it's not even relatively close to the original issue, so no, +1 is not "the same problem", please, report a separate issue and provide this logs and other information such us ionic version, cordova-plugin-ionic version, cordova-plugin-ionic-webview version or the whole package.json if possible.

**Comment by HudsonAfonso** [comment]
It's okay if you do not want to help, just do not answer.
thank you

**Comment by jcesarmobile** [comment]
I'm telling you it's not the same issue, it's a totally different one, so I told you to create a new issue so it can be properly tracked, keeping this one separated.

**Comment by OutsourceNow** [comment]
I am having the same issue, I get this in console. Any ideas?

[app-scripts] [00:40:12]  console.log: calling _sync
[app-scripts] [00:40:14]  console.log: Starting IonicTimer CleanSnapshotDir
[app-scripts] [00:40:14]  console.log: Finished IonicTimer CleanSnapshotDir in 0.153 seconds.
[app-scripts] [00:40:14]  console.log: Cleaned version directory
[app-scripts] [00:40:14]  console.log: Starting IonicTimer CopyBaseApp
[app-scripts] [00:40:17]  console.log: Finished IonicTimer CopyBaseApp in 2.933 seconds.
[app-scripts] [00:40:17]  console.log: Copied base app resources
[app-scripts] [00:40:17]  console.log: Downloading update...
[app-scripts] [00:40:17]  console.log: Starting IonicTimer downloadTimer
[app-scripts] [00:40:17]  console.log: About to download 188 new files for update.
[app-scripts] [00:40:19]  console.log: Message: downloaded batch 1 of 10 downloads. Done downloading 20 of 188 files Diff
IonicTimer
[app-scripts]             downloadTimer in 1.484 seconds.
[app-scripts] [00:40:20]  console.log: Message: downloaded batch 2 of 10 downloads. Done downloading 40 of 188 files Diff
IonicTimer
[app-scripts]             downloadTimer in 0.624 seconds.
[app-scripts] [00:40:20]  console.log: Message: downloaded batch 3 of 10 downloads. Done downloading 60 of 188 files Diff
IonicTimer
[app-scripts]             downloadTimer in 0.537 seconds.
[app-scripts] [00:40:21]  console.log: Message: downloaded batch 4 of 10 downloads. Done downloading 80 of 188 files Diff
IonicTimer
[app-scripts]             downloadTimer in 0.542 seconds.
[app-scripts] [00:40:27]  console.log: Message: downloaded batch 5 of 10 downloads. Done downloading 100 of 188 files Diff IonicTimer
[app-scripts]             downloadTimer in 6.804 seconds.
[app-scripts] [00:40:34]  console.log: Message: downloaded batch 6 of 10 downloads. Done downloading 120 of 188 files Diff IonicTimer
[app-scripts]             downloadTimer in 6.447 seconds.
[app-scripts] [00:40:35]  console.log: Message: downloaded batch 7 of 10 downloads. Done downloading 140 of 188 files Diff IonicTimer
[app-scripts]             downloadTimer in 0.661 seconds.
[app-scripts] [00:40:35]  console.log: Message: downloaded batch 8 of 10 downloads. Done downloading 160 of 188 files Diff IonicTimer
[app-scripts]             downloadTimer in 0.959 seconds.
[app-scripts] [00:40:36]  console.warn: [object Object]
[app-scripts] [00:40:36]  console.warn: Sync failed. Defaulting to last available version.
[app-scripts] [00:40:36]  console.log: calling _reload
[app-scripts] [00:40:36]  console.log: done _reloading

**Comment by allurco** [comment]
I removed Android Platform because of this and now I am not able to re-add it:
```
Installing "cordova-plugin-ionic" for android
Failed to install 'cordova-plugin-ionic': Error: Variable(s) missing: APP_ID, CHANNEL_NAME
    at Object.mergeVariables (C:\Users\roger\Documents\thatsmine\node_modules\cordova\node_modules\cordova-lib\src\plugman\variable-merge.js:58:15)
    at C:\Users\roger\Documents\thatsmine\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:315:44
    at _fulfilled (C:\Users\roger\Documents\thatsmine\node_modules\cordova\node_modules\q\q.js:854:54)
    at C:\Users\roger\Documents\thatsmine\node_modules\cordova\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\roger\Documents\thatsmine\node_modules\cordova\node_modules\q\q.js:816:13)
    at C:\Users\roger\Documents\thatsmine\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\roger\Documents\thatsmine\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\roger\Documents\thatsmine\node_modules\cordova\node_modules\q\q.js:125:13)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
Variable(s) missing: APP_ID, CHANNEL_NAME
```
All my variables are on the XML and package.json:

```
<plugin name="cordova-plugin-ionic" spec="^5.2.7">
        <variable name="APP_ID" value="6ccf63d5" />
        <variable name="CHANNEL_NAME" value="Master" />
        <variable name="UPDATE_METHOD" value="auto" />
        <variable name="UPDATE_API" value="https://api.ionicjs.com" />
        <variable name="MAX_STORE" value="2" />
        <variable name="MIN_BACKGROUND_DURATION" value="30" />
    </plugin>
```

I am sure this is related.
