### ISSUE TITLE
Error on live reload

### ISSUE THREAD

**Issue by DavidTalamona** [ionic-team/cordova-plugin-ionic#29]
When running my app on an android device with livereload it works initially but the first change / livereload and every one that follows causes the following javascript error.

Message copied from my IONIC dashboard (https://dashboard.ionicjs.com/app/39922ef6/monitoring/exceptions/a7441695a8c98539c288830ae0b604563921c0f2):
```
Exception Detail

TypeError: Cannot read property 'deploy' of undefined
at new Pro (vendor.js:74456:55)
at _createClass (vendor.js:10972:20)
at _createProviderInstance$1 (vendor.js:10948:26)
at resolveNgModuleDep (vendor.js:10933:17)
at _createClass (vendor.js:10982:32)
at _createProviderInstance$1 (vendor.js:10948:26)
at resolveNgModuleDep (vendor.js:10933:17)
at _createClass (vendor.js:10982:32)
at _createProviderInstance$1 (vendor.js:10948:26)
at resolveNgModuleDep (vendor.js:10933:17)

Original Stacktrace

Cannot read property 'deploy' of undefined
at new Pro (vendor.js:74456:55)
at _createClass (vendor.js:10972:20)
at _createProviderInstance$1 (vendor.js:10948:26)
at resolveNgModuleDep (vendor.js:10933:17)
at _createClass (vendor.js:10982:32)
at _createProviderInstance$1 (vendor.js:10948:26)
at resolveNgModuleDep (vendor.js:10933:17)
at _createClass (vendor.js:10982:32)
at _createProviderInstance$1 (vendor.js:10948:26)
at resolveNgModuleDep (vendor.js:10933:17)
```

I implemented the Ionic pro's live update manually ("none" mode) like this:
```
this.ionicPro.deploy.init({channel: 'Production', appId: '39922ef6'}).then(() => {
	this.ionicPro.deploy.check().then(snapshotAvailable => {
		if (snapshotAvailable === 'true') {
			this.showLoader({content: `<div class="text-center">${this.config.i18n.update.installing}<br>0%</div>`}).then(() =>
				this.ionicPro.deploy.download().subscribe(downloadStaus => {
					if (downloadStaus === 'true') {
						this.ionicPro.deploy.extract().subscribe(extractStaus => {
							if (extractStaus === 'true' || extractStaus === 'done') {
								this.hideLoader().then(() =>
									this.alert(this.config.i18n.update.done, null, {onDidDismiss: () => {
										this.splashScreen.show();
										this.ionicPro.deploy.redirect(); // reloads the app / webview
									}})
								)
							} else {
								this.setUpdateProgress(50 + (Number(extractStaus) / 2));
							}
						}, e => noUpdateAvailable(e));
					} else {
						this.setUpdateProgress(Number(downloadStaus) / 2);
					}
				}, e => noUpdateAvailable(e))
			);
		} else {
			noUpdateAvailable();
		}
	}, () => noUpdateAvailable());
}, () => noUpdateAvailable());
```
This code is executed on every app start, resume and also on live reload.
Think `ionicPro.deploy.init` cannot be called multiple times!?

**!!! UPDATE: I commented all the pro plugin code out and still get the same issue. Seems like it is the pure presence of the plugin causing the error !!!**

### My environment info:
```
cli packages: (C:\www\localhost\touch\ionic2\PLC\PlusCash\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.4.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.3
    npm               : 4.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Program Files (x86)\Android\android-sdk

Misc:

    backend : pro
```

**Comment by DavidTalamona** [comment]
Just discovered the source of this error is not the plugin itself but the ionic native wrapper package.
Opened an issue there: https://github.com/ionic-team/ionic-native/issues/2136
Closing this issue.

**Comment by ibcooley** [comment]
@DavidTalamona Are you sure it isn't, for some reason, that the cordova-plugin-ionic isnt registering properly on your device?  I'm running into the same issue, and the more I think about it -- i feel like cordova-plugin-ionic is not registering properly.

**Comment by DavidTalamona** [comment]
@ibcooley See my comment to your question here: ionic-team/ionic-native#2136
