### ISSUE TITLE
Ionic cordova does not build with --keystore without Xorg server

### ISSUE THREAD

**Issue by pickfire** [ionic-team/cordova-plugin-ionic#39]
The need for ionic cordova to build over ssh fails when **Xorg server is not available** to be used to display the java ugly looking password prompt. Thus
```
> cordova build android --release --device -- --keystore=my-release-key.keystore --alias=alias_name --minSdkVersion=21
ANDROID_HOME=/opt/android-sdk
JAVA_HOME=/usr/lib/jvm/java-8-openjdk
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

        at build_a28o7epn5kyydakukpqtoxwly.run(/tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/build.gradle:141)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

Incremental java compilation is an incubating feature.

The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.


FAILURE: Build failed with an exception.

* Where:
Script '/tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/CordovaLib/cordova.gradle' line: 143

* What went wrong:
Failed to create component for 'dialog' reason: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
>
  No X11 DISPLAY variable was set, but this program performed an operation which requires it.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.598 secs
(node:18291) UnhandledPromiseRejectionWarning: Error: /tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/CordovaLib/cordova.gradle' line: 143

* What went wrong:
Failed to create component for 'dialog' reason: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
>
  No X11 DISPLAY variable was set, but this program performed an operation which requires it.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:18291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside
of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Is there anyway sane way for ionic cordova to just prompt for the password rather than abandoning the build?

**Comment by jrobeson** [comment]
also, this likely wouldn't work under DEs that speak Wayland either.

**Comment by pickfire** [comment]
@jrobeson Well, people could still use xwayland to avoid that I guess?

**Comment by Fuiste** [comment]
This repo is for Ionic Pro's native plugin.  For help with the Ionic CLI (and by extension the build step), check out the CLI repo -> https://github.com/ionic-team/ionic-cli

Sorry for the confusion there.
